"""empty message

Revision ID: 144b376b53a1
Revises: 
Create Date: 2018-03-13 14:23:54.470542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144b376b53a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_email'), 'admin', ['email'], unique=True)
    op.create_index(op.f('ix_admin_username'), 'admin', ['username'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.Column('goal_period', sa.String(length=16), nullable=True),
    sa.Column('wc_id', sa.Integer(), nullable=True),
    sa.Column('wc_token', sa.String(length=128), nullable=True),
    sa.Column('fb_token', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wc_id')
    )
    op.create_index(op.f('ix_user_registered_on'), 'user', ['registered_on'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('expiration', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_activity_id'), 'activity', ['activity_id'], unique=True)
    op.create_index(op.f('ix_activity_end_time'), 'activity', ['end_time'], unique=False)
    op.create_index(op.f('ix_activity_expiration'), 'activity', ['expiration'], unique=False)
    op.create_index(op.f('ix_activity_start_time'), 'activity', ['start_time'], unique=False)
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('daily_progress', sa.Float(), nullable=True),
    sa.Column('weekly_progress', sa.Float(), nullable=True),
    sa.Column('step_count', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_timestamp'), 'log', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_timestamp'), table_name='log')
    op.drop_table('log')
    op.drop_index(op.f('ix_activity_start_time'), table_name='activity')
    op.drop_index(op.f('ix_activity_expiration'), table_name='activity')
    op.drop_index(op.f('ix_activity_end_time'), table_name='activity')
    op.drop_index(op.f('ix_activity_activity_id'), table_name='activity')
    op.drop_table('activity')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_registered_on'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_admin_username'), table_name='admin')
    op.drop_index(op.f('ix_admin_email'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
